In [1]:
import numpy as np

In [2]:
d = np.array([1,2,3])

In [3]:
print(d)

[1 2 3]


In [4]:
#Question 1: Addition, Multiplication, division and exponentiation
l1 = np.array([1,2,3])
l2 = np.array([1,2,3])
res = l1+l2
print("Addition: ", res)

Addition:  [2 4 6]


In [5]:
#Subtraction
res = l1 - l2
print(res)

[0 0 0]


In [6]:
#Multiplication
res = l1 * l2
print(res)

[1 4 9]


In [7]:
#Division
res = l1/l2
print(res)

[1. 1. 1.]


In [8]:
#exponentiation
res = l1**l2
print(res)

[ 1  4 27]


In [9]:
#Question 2: logical operations OR, AND, Cheching the equality, NOT, XOR

In [10]:
#Logical And
a = np.logical_and(True, False)
b = np.logical_and(True, True)
c = np.logical_and(False, True)
d = np.logical_and(False, False)
print("l: ",a, b, c, d)
l = np.array([a,b,c,d])
l2 = np.array([True, True, False, False])
res = l==l2
print(res)

l:  False True False False
[False  True  True  True]


In [11]:
#Logical Or
a = np.logical_or(True, False)
b = np.logical_or(True, True)
c = np.logical_or(False, True)
d = np.logical_or(False, False)
print("l: ",a, b, c, d)
l = np.array([a,b,c,d])
l2 = np.array([True, True, False, False])
res = l==l2
print(res)

l:  True True True False
[ True  True False  True]


In [12]:
#Logical xor
a = np.logical_xor(True, False)
b = np.logical_xor(True, True)
c = np.logical_xor(False, True)
d = np.logical_xor(False, False)
print("l: ",a, b, c, d)
l = np.array([a,b,c,d])
l2 = np.array([True, True, False, False])
res = l==l2
print(res)

l:  True False True False
[ True False False  True]


In [13]:
#Cheching the equality
l = np.array([1,2,3])
l2 = np.array([1,2,3])
res = l==l2
print(res)


[ True  True  True]


In [14]:
#Question 3: Create, initialize, display simple variables and simple strings and use simple
#formatting for variable
arr = eval(input("Enter an array:"))
print(type(arr))
a = np.array(arr)
a2 = np.array([1,2,3])
print(type(a2))
print(type(a))
string = input("Enter any string:")
print("Entered string: {}".format(string))


<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Entered string: hello


In [15]:
#Question 4: Create define single dimension/ multi dimension arrays with specific values like array of all ones,
# all zeroes, array with random values within a rangeor a diagonal matrix

In [16]:
#single dimension
arr = np.array([1,2,3])
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)

Shape of the array:  (3,)
Dimension of the array:  1


In [17]:
#multi dimension arrays
arr = np.array([[1,2,3], [1,2,3]])
print(arr)
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)
arr = np.array([[1,2,3], [1,2,3], [1,2,3]])
print(arr)
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)
arr = np.array([[[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]])
print(arr)
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)

[[1 2 3]
 [1 2 3]]
Shape of the array:  (2, 3)
Dimension of the array:  2
[[1 2 3]
 [1 2 3]
 [1 2 3]]
Shape of the array:  (3, 3)
Dimension of the array:  2
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
Shape of the array:  (2, 3, 3)
Dimension of the array:  3


In [18]:
#all ones
arr = np.ones(2)
print(arr)

[1. 1.]


In [19]:
#all zeroes
arr = np.zeros(2)
print(arr)

[0. 0.]


In [20]:
#array with random values within a range or a diagonal matrix
arr = np.random.rand(3)
print(arr)
arr2 = np.random.uniform([3,3])
print(arr2)
arr3 = np.random.uniform(1, 10, (3,3))
print(arr3)

[0.43768998 0.98619986 0.27922086]
[2.68470576 2.78131132]
[[7.60982186 7.18264602 1.17981146]
 [2.74039573 6.2341422  8.91671065]
 [3.29950312 4.32221498 1.48170274]]


In [21]:
arr4 = np.diag(np.random.rand(3))
print(arr4)

[[0.59860461 0.         0.        ]
 [0.         0.49020705 0.        ]
 [0.         0.         0.38171808]]


In [22]:
#Q5. Use command to compute the size of a matrix, size/length of a particular row/column, load
#data from a text file, store matrix data to a text file, finding out variables and their
# features in the current scope.

In [23]:
#Compute the size of a matrix, size/length of a particular row/column:
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])
length = matrix.size
#Size of row 1
row_size = matrix[1,:].size
#Size of coloumn 2
col_size = matrix[:,2].size
print("Matrix Size:", length)
print("Size of Row 1:", row_size)
print("Size of Column 2:", col_size)

Matrix Size: 9
Size of Row 1: 3
Size of Column 2: 3


In [25]:
# Load data from a text file
loaded_data = np.loadtxt('populations.txt')

print("Loaded Data:")
print(loaded_data)

# Create a sample matrix
matrix_to_store = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Store matrix data to a text file
np.savetxt('output.txt', matrix_to_store)

print("Matrix data stored to output.txt")
print("Displaying Matrix data")
l = np.loadtxt('output.txt')
print(l)


Loaded Data:
[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]
Matrix data stored to output.txt
Displaying Matrix data
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [28]:
#Q6. Perform basic operations on matrices (like addition, subtraction, multiplication) and display
#specific rows or columns of the matrix.
m1 = np.array([[1,1,1], [1,1,1], [1,1,1]])
m2 = np.array([[1,2,3], [1,1,2], [2,1,3]])
m3 = m1+m2
print("Addition of two matrices are:", m3)
m3 = m2 - m1
print("Subtraction of two matrices are:", m3)
m3 = m1*m2
print("Multiplication of two matrices are:", m3)
#Displaying specific rows and coloumns of the matrix
print("Displaying 1st coloumn of the m1 matrix:")
print(m1[:,1])

Addition of two matrices are: [[2 3 4]
 [2 2 3]
 [3 2 4]]
Subtraction of two matrices are: [[0 1 2]
 [0 0 1]
 [1 0 2]]
Multiplication of two matrices are: [[1 2 3]
 [1 1 2]
 [2 1 3]]
Displaying 1st coloumn of the m1 matrix:
[1 1 1]


In [ ]:
#Q7. Perform other matrix operations like converting matrix data to absolute values, taking the
# negative of matrix values, additing/removing rows/columns from a matrix, finding the maximum
# or minimum values in a matrix or in a row/column, and finding the sum of some/all
# elements in a matrix.


# Create a sample matrix
matrix = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])

# Convert matrix data to absolute values
absolute_matrix = np.abs(matrix)

print("Original Matrix:")
print(matrix)
print("\nMatrix with Absolute Values:")
print(absolute_matrix)


In [ ]:
# Create a sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Take the negative of matrix values
negative_matrix = -matrix

print("Original Matrix:")
print(matrix)
print("\nMatrix with Negative Values:")
print(negative_matrix)


In [ ]:
# Create a sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Add a new row
new_row = np.array([10, 11, 12])
matrix_with_new_row = np.vstack((matrix, new_row))

# Add a new column
new_column = np.array([13, 14, 15])
matrix_with_new_column = np.hstack((matrix, new_column.reshape(-1, 1)))

# Remove the second row and third column
matrix_removed_row_column = np.delete(np.delete(matrix, 1, axis=0), 2, axis=1)

print("Original Matrix:")
print(matrix)
print("\nMatrix with New Row:")
print(matrix_with_new_row)
print("\nMatrix with New Column:")
print(matrix_with_new_column)
print("\nMatrix with Second Row and Third Column Removed:")
print(matrix_removed_row_column)


In [ ]:
# Create a sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Add a new row
new_row = np.array([10, 11, 12])
matrix_with_new_row = np.vstack((matrix, new_row))

# Add a new column
new_column = np.array([13, 14, 15])
matrix_with_new_column = np.hstack((matrix, new_column.reshape(-1, 1)))

# Remove the second row and third column
matrix_removed_row_column = np.delete(np.delete(matrix, 1, axis=0), 2, axis=1)

print("Original Matrix:")
print(matrix)
print("\nMatrix with New Row:")
print(matrix_with_new_row)
print("\nMatrix with New Column:")
print(matrix_with_new_column)
print("\nMatrix with Second Row and Third Column Removed:")
print(matrix_removed_row_column)


In [ ]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 5, 3], [4, 2, 6], [7, 8, 9]])

# Find the maximum value in the entire matrix
max_value = np.max(matrix)

# Find the minimum value in the entire matrix
min_value = np.min(matrix)

# Find the maximum value in each column
max_values_columns = np.max(matrix, axis=0)

# Find the minimum value in each row
min_values_rows = np.min(matrix, axis=1)

print("Original Matrix:")
print(matrix)
print("\nMaximum Value in the Matrix:", max_value)
print("Minimum Value in the Matrix:", min_value)
print("\nMaximum Values in Each Column:")
print(max_values_columns)
print("\nMinimum Values in Each Row:")
print(min_values_rows)
