In [ ]:
#a) Create a 5X2 integer array with elements in the range 500 to 100 such that the different between each element is 5. Reshape the resultant array to size 10*1

In [3]:
import numpy as np
import pandas as pd

# Create the 5x2 array with elements in the range 500 to 100 with a difference of 5
arr = np.arange(500, 100, -5)[:10].reshape(5, 2)

# Reshape the array to size 10x1
reshaped_arr = arr.reshape(10, 1)

# Convert the reshaped array to a DataFrame using Pandas
df = pd.DataFrame(reshaped_arr)

print("Original array (5x2):")
print(arr)
print("\nReshaped array (10x1):")
print(reshaped_arr)
print("\nDataFrame:")
print(df)


Original array (5x2):
[[500 495]
 [490 485]
 [480 475]
 [470 465]
 [460 455]]

Reshaped array (10x1):
[[500]
 [495]
 [490]
 [485]
 [480]
 [475]
 [470]
 [465]
 [460]
 [455]]

DataFrame:
     0
0  500
1  495
2  490
3  485
4  480
5  475
6  470
7  465
8  460
9  455


In [4]:
# b) Cretae a 1d random array comprising elements in range 1 to 100. Compute the minimum, maximum, mean, median, standard deviation, unique values and count of unique values.
import numpy as np

# Create a 1D random array with elements in the range 1 to 100
random_array = np.random.randint(1, 101, size=100)

# Compute minimum, maximum, mean, median, and standard deviation
minimum = np.min(random_array)
maximum = np.max(random_array)
mean = np.mean(random_array)
median = np.median(random_array)
std_dev = np.std(random_array)

# Compute unique values and count of unique values
unique_values = np.unique(random_array)
count_unique = len(unique_values)

print("Random Array:", random_array)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Unique Values:", unique_values)
print("Count of Unique Values:", count_unique)


Random Array: [93 89 75 33 62 98 64 26 20 91 38 68 93 80 35 44 12 35 60 64 53 12 84 93
 53 11 35  4  3 60 55 71 20 77 29 16 51 80 44 94 52 93 69 15 31 56 27 88
 24 60 78 11 69 83 24 19  4 50 44 47 58 62 29 96 52 59  1 45 19 68 89 73
 87 72 42 16 73  5  4 32 10 52 64 12 27 29  6 12 83 73 55 64 78 93 78 71
 68 82 42 67]
Minimum: 1
Maximum: 98
Mean: 51.17
Median: 54.0
Standard Deviation: 28.00037678317919
Unique Values: [ 1  3  4  5  6 10 11 12 15 16 19 20 24 26 27 29 31 32 33 35 38 42 44 45
 47 50 51 52 53 55 56 58 59 60 62 64 67 68 69 71 72 73 75 77 78 80 82 83
 84 87 88 89 91 93 94 96 98]
Count of Unique Values: 57


In [5]:
#Add two 2D arrays and calculate the square root of each element of the resulting array
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Add the two arrays
sum_array = array1 + array2

# Calculate the square root of each element of the resulting array
sqrt_array = np.sqrt(sum_array)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nSum of the arrays:")
print(sum_array)
print("\nSquare root of each element of the resulting array:")
print(sqrt_array)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Sum of the arrays:
[[ 6  8]
 [10 12]]

Square root of each element of the resulting array:
[[2.44948974 2.82842712]
 [3.16227766 3.46410162]]


In [6]:
#Consider the following array: intArray = numpy.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]) Perform each of the following operations on the original array as given above: i) Delete the second column of the array. ii) Sort the array by the second row. iii) Sort the array by second column. iv) Find row-wise maximum element. v) Find column wise maximum element vi) Swap the first two columns of the array. vii) Retrieve all the even numbers from the array.
import numpy as np

# Given array
intArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# i) Delete the second column of the array
intArray_without_second_column = np.delete(intArray, 1, axis=1)

# ii) Sort the array by the second row
sorted_by_second_row = intArray[:, intArray[1].argsort()]

# iii) Sort the array by the second column
sorted_by_second_column = intArray[intArray[:,1].argsort()]

# iv) Find row-wise maximum element
row_max = np.max(intArray, axis=1)

# v) Find column-wise maximum element
col_max = np.max(intArray, axis=0)

# vi) Swap the first two columns of the array
swapped_columns = np.copy(intArray)
swapped_columns[:, [0, 1]] = swapped_columns[:, [1, 0]]

# vii) Retrieve all the even numbers from the array
even_numbers = intArray[intArray % 2 == 0]

print("Original Array:")
print(intArray)
print("\ni) Array after deleting the second column:")
print(intArray_without_second_column)
print("\nii) Array sorted by the second row:")
print(sorted_by_second_row)
print("\niii) Array sorted by the second column:")
print(sorted_by_second_column)
print("\niv) Row-wise maximum element:")
print(row_max)
print("\nv) Column-wise maximum element:")
print(col_max)
print("\nvi) Array after swapping the first two columns:")
print(swapped_columns)
print("\nvii) Even numbers from the array:")
print(even_numbers)


Original Array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

i) Array after deleting the second column:
[[34 73]
 [82 12]
 [53 66]]

ii) Array sorted by the second row:
[[73 43 34]
 [12 22 82]
 [66 94 53]]

iii) Array sorted by the second column:
[[82 22 12]
 [34 43 73]
 [53 94 66]]

iv) Row-wise maximum element:
[73 82 94]

v) Column-wise maximum element:
[82 94 73]

vi) Array after swapping the first two columns:
[[43 34 73]
 [22 82 12]
 [94 53 66]]

vii) Even numbers from the array:
[34 82 22 12 94 66]


In [7]:
#Create an identity matrix of size 5X5 with all the diagonal elements set to value 5
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Replace the diagonal elements with the value 5
identity_matrix *= 5

print(identity_matrix)


[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [ ]:
#Write a python program using pandas library to perform the following operations:

In [8]:
#a) Create a series from a dictionarry representing the count of the students in each class X, XI, XII as given below. dictionary = {'XII': 25, 'XI': 30, 'X': 50} Display the series i)Sorted on the index ii)Sorted on values
import pandas as pd

# Given dictionary representing the count of students in each class
dictionary = {'XII': 25, 'XI': 30, 'X': 50}

# Create a series from the dictionary
students_series = pd.Series(dictionary)

# Display the series sorted on index
sorted_by_index = students_series.sort_index()

# Display the series sorted on values
sorted_by_values = students_series.sort_values()

print("Series sorted on index:")
print(sorted_by_index)

print("\nSeries sorted on values:")
print(sorted_by_values)


Series sorted on index:
X      50
XI     30
XII    25
dtype: int64

Series sorted on values:
XII    25
XI     30
X      50
dtype: int64


In [9]:
#b) Create a series from the numpy array of 10 randomly generated values. Find the maximum and minimum values and their positions.
import numpy as np
import pandas as pd

# Generate a NumPy array of 10 randomly generated values
random_array = np.random.rand(10)

# Create a Pandas Series from the NumPy array
random_series = pd.Series(random_array)

# Find maximum and minimum values
max_value = random_series.max()
min_value = random_series.min()

# Find positions of maximum and minimum values
max_position = random_series.idxmax()
min_position = random_series.idxmin()

print("Random Series:")
print(random_series)
print("\nMaximum value:", max_value)
print("Position of maximum value:", max_position)
print("\nMinimum value:", min_value)
print("Position of minimum value:", min_position)


Random Series:
0    0.512969
1    0.030445
2    0.122536
3    0.018614
4    0.948277
5    0.014205
6    0.504773
7    0.127752
8    0.699876
9    0.305689
dtype: float64

Maximum value: 0.9482769863588214
Position of maximum value: 4

Minimum value: 0.014204535162469
Position of minimum value: 5
