In [1]:
import numpy as np

In [2]:
d = np.array([1,2,3])

In [3]:
print(d)

[1 2 3]


In [4]:
#Question 1: Addition, Multiplication, division and exponentiation
l1 = np.array([1,2,3])
l2 = np.array([1,2,3])
res = l1+l2
print("Addition: ", res)

Addition:  [2 4 6]


In [5]:
#Subtraction
res = l1 - l2
print(res)

[0 0 0]


In [6]:
#Multiplication
res = l1 * l2
print(res)

[1 4 9]


In [7]:
#Division
res = l1/l2
print(res)

[1. 1. 1.]


In [8]:
#exponentiation
res = l1**l2
print(res)

[ 1  4 27]


In [9]:
#Question 2: logical operations OR, AND, Cheching the equality, NOT, XOR

In [10]:
#Logical And
a = np.logical_and(True, False)
b = np.logical_and(True, True)
c = np.logical_and(False, True)
d = np.logical_and(False, False)
print("l: ",a, b, c, d)
l = np.array([a,b,c,d])
l2 = np.array([True, True, False, False])
res = l==l2
print(res)

l:  False True False False
[False  True  True  True]


In [11]:
#Logical Or
a = np.logical_or(True, False)
b = np.logical_or(True, True)
c = np.logical_or(False, True)
d = np.logical_or(False, False)
print("l: ",a, b, c, d)
l = np.array([a,b,c,d])
l2 = np.array([True, True, False, False])
res = l==l2
print(res)

l:  True True True False
[ True  True False  True]


In [12]:
#Logical xor
a = np.logical_xor(True, False)
b = np.logical_xor(True, True)
c = np.logical_xor(False, True)
d = np.logical_xor(False, False)
print("l: ",a, b, c, d)
l = np.array([a,b,c,d])
l2 = np.array([True, True, False, False])
res = l==l2
print(res)

l:  True False True False
[ True False False  True]


In [13]:
#Cheching the equality
l = np.array([1,2,3])
l2 = np.array([1,2,3])
res = l==l2
print(res)


[ True  True  True]


In [15]:
#Question 3: Create, initialize, display simple variables and simple strings and use simple
#formatting for variable
arr = eval(input("Enter an array:"))
print(type(arr))
a = np.array(arr)
a2 = np.array([1,2,3])
print(type(a2))
print(type(a))
string = input("Enter any string:")
print("Entered string: {}".format(string))


<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Entered string: hello


In [ ]:
#Question 4: Create define single dimension/ multi dimension arrays with specific values like array of all ones,
# all zeroes, array with random values within a rangeor a diagonal matrix

In [ ]:
#single dimension
arr = np.array([1,2,3])
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)

Shape of the array:  (3,)
Dimension of the array:  1


In [ ]:
#multi dimension arrays
arr = np.array([[1,2,3], [1,2,3]])
print(arr)
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)
arr = np.array([[1,2,3], [1,2,3], [1,2,3]])
print(arr)
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)
arr = np.array([[[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]])
print(arr)
print("Shape of the array: ",arr.shape)
print("Dimension of the array: ",arr.ndim)

[[1 2 3]
 [1 2 3]]
Shape of the array:  (2, 3)
Dimension of the array:  2
[[1 2 3]
 [1 2 3]
 [1 2 3]]
Shape of the array:  (3, 3)
Dimension of the array:  2
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
Shape of the array:  (2, 3, 3)
Dimension of the array:  3


In [ ]:
#all ones
arr = np.ones(2)
print(arr)

[1. 1.]


In [ ]:
#all zeroes
arr = np.zeros(2)
print(arr)

[0. 0.]


In [ ]:
#array with random values within a range or a diagonal matrix
arr = np.random.rand(3)
print(arr)
arr2 = np.random.uniform([3,3])
print(arr2)
arr3 = np.random.uniform(1, 10, (3,3))
print(arr3)

[0.01150664 0.81391447 0.48873076]
[1.05316171 2.90853624]
[[9.12404472 6.40764319 1.25995676]
 [3.5628961  3.0379637  3.438712  ]
 [7.70547069 5.33291877 1.82711738]]


In [ ]:
arr4 = np.diag(np.random.rand(3))
print(arr4)

[[0.37541244 0.         0.        ]
 [0.         0.69851171 0.        ]
 [0.         0.         0.59118955]]


In [ ]:
#Q5. Use command to compute the size of a matrix, size/length of a particular row/column, load
#data from a text file, store matrix data to a text file, finding out variables and their
# features in the current scope.

In [16]:
#Compute the size of a matrix, size/length of a particular row/column:
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])
length = matrix.size
#Size of row 1
row_size = matrix[1,:].size
#Size of coloumn 2
col_size = matrix[:,2].size
print("Matrix Size:", length)
print("Size of Row 1:", row_size)
print("Size of Column 2:", col_size)

Matrix Size: 9
Size of Row 1: 3
Size of Column 2: 3
